import React, { useEffect, useState } from "react";
import PropTypes from "prop-types";
import { toDataUrl } from "../utils/toDataUrl";


const MiniFlyer = React.forwardRef(function MiniFlyer({ item }, frameRef) {
    const url = typeof window !== "undefined" ? window.location.href : "";
    const [imgDataUrl, setImgDataUrl] = useState(null);

    const statusColor =
        item.status === "Open" ? "#16A34A" : item.status === "Claimed" ? "#d10404" : "#ffc400";

    useEffect(() => {
        let cancelled = false;
        (async () => {
            try {
                if (!item.photoUrl) { setImgDataUrl(null); return; }
                const data = await toDataUrl(item.photoUrl);
                if (!cancelled) setImgDataUrl(data);
            } catch { setImgDataUrl(null); }
        })();
        return () => { cancelled = true; };
    }, [item.photoUrl]);

    const safe = (s) => String(s ?? "").replace(/</g, "&lt;");

    const html = `<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<style>
  html,body { margin:0; padding:0; }
  /* A5 portrait canvas: 794×1123 */
  body {
    width:794px; height:1123px; box-sizing:border-box;
    background:#FFFFFF; color:#0F172A;
    font-family: Arial, Helvetica, sans-serif; padding: 40px 30px;
    border:16px solid #E5E7EB;
  }

  .brand { font-size:24px; font-weight:700; letter-spacing:.2px; margin:0 0 8px 0; }
  .title { font-size:40px; font-weight:800; margin:0 0 8px 0; line-height:1.5; }
  .meta  { font-size:16px; color:#334155; margin:0; }

  .badges { margin-top:12px; display:flex; gap:10px; align-items:center; }
  .pill {
    font-size:16px; font-weight:700; color:#0F172A; word-break:break-all;
  }
  .pill-status { color:${statusColor} ; border-color:${statusColor}; }

  .photo-wrap {
    margin-top:16px;
    width:100%; height:520px;
    background:#F8FAFC; border:1px solid #E2E8F0; border-radius:12px;
    display:flex; align-items:center; justify-content:center; overflow:hidden;
  }
  .photo { max-width:100%; max-height:100%; object-fit:contain; display:block; }

  .info {
    margin-top:16px; display:grid; grid-template-columns: 1fr 1fr; gap:12px;
    font-size:15px; color:#111827;
  }
  .info .label { color:#6B7280; font-weight:700; font-size:13px; margin-bottom:4px; }
  .info .box {
    border:1px solid #E5E7EB; border-radius:10px; padding:10px 12px; min-height:44px; background:#FFFFFF;
  }

  .rule { height:1px; background:#E5E7EB; margin:18px 0; }

  .url {
    font-size:18px; font-weight:700; color:#0000FF;
    border:1px solid #CBD5E1; background:#F8FAFC; border-radius:10px;
    padding:10px 12px; word-break:break-all;
  }
  .hint { font-size:12px; color:#6B7280; margin-top:6px; }
</style>
</head>
<body>
  <div>
    <div class="brand">Back2U — Campus Lost & Found</div>
    <div class="title">${safe(item.title)}</div>
    <div class="badges">
      <span class="pill">Category: ${safe(item.category || "Unknown")}</span>
      <span> | </span>
      <span class="pill pill-status">Status: ${safe(item.status || "Open")}</span>
    </div>

    <div class="photo-wrap">
      <img class="photo" alt="">
    </div>

    <div class="info">
      <div class="box">
        <div class="label">Listed at</div>
        <div>${safe(item.date || "—")}</div>
      </div>
      <div class="box">
        <div class="label">Tag / ID</div>
        <div>${safe(item._id)}</div>
      </div>
    </div>

    <div class="rule"></div>
    <div class="url">Item Link: ${safe(url)}</div>
    <div class="hint">Login required to view details • Auto generated by Back2U</div>
  </div>
</body>
</html>`;

    useEffect(() => {
        const iframe = frameRef?.current;
        if (!iframe) return;

        function inject() {
            const doc = iframe.contentDocument || iframe.contentWindow?.document;
            if (!doc) return;
            const img = doc.querySelector(".photo");
            if (!img) return;
            if (imgDataUrl) img.setAttribute("src", imgDataUrl);
        }

        const onLoad = () => inject();
        iframe.addEventListener("load", onLoad);
        inject();
        return () => iframe.removeEventListener("load", onLoad);
    }, [frameRef, imgDataUrl]);

    return (
        <iframe
            ref={frameRef}
            srcDoc={html}
            style={{ position: "absolute", left:-10000, top: 0, width: 794, height: 1123, border: 0 }}
            title="mini-flyer"
        />
    );
});
export default MiniFlyer;

MiniFlyer.propTypes = { item: PropTypes.object.isRequired };